experiment_name: "base_line_model"
max_epochs: 25
n_trials: 10
seed: 0
loss_type: "triplet"
best_pairs_dataset: "C:\\Users\\simon\\Projets\\FindingMnemo\\src\\pairing\\dataset\\pairing\\best_pairs.csv"
worst_pairs_dataset: "C:\\Users\\simon\\Projets\\FindingMnemo\\src\\pairing\\dataset\\pairing\\worst_pairs.csv"
log_folder: "file:C:\\Users\\simon\\Projets\\FindingMnemo\\mlruns\\"
model_type: naive_baseline